import {
  pgTable,
  text,
  integer,
  doublePrecision,
  boolean,
  jsonb,
  serial,
} from "drizzle-orm/pg-core";
import type { Badge, Segment, OrderItem } from "./types";

export const products = pgTable("products", {
  id: text("id").primaryKey(),
  seq: serial("seq"),
  slug: text("slug").notNull().unique(),
  name: text("name").notNull(),
  emoji: text("emoji").notNull().default("📦"),
  gradient: text("gradient").notNull().default(""),
  imageUrl: text("image_url"),
  videoUrl: text("video_url"),
  category: text("category").notNull().default("General"),
  grupoIds: jsonb("grupo_ids").$type<string[]>().notNull().default([]),
  tagline: text("tagline").notNull().default(""),
  description: text("description").notNull().default(""),
  retail: doublePrecision("retail").notNull().default(0),
  wholesale: doublePrecision("wholesale").notNull().default(0),
  moq: integer("moq").notNull().default(1),
  unitsPerCase: integer("units_per_case").notNull().default(1),
  badges: jsonb("badges").$type<Badge[]>().notNull().default([]),
  tags: jsonb("tags").$type<string[]>().notNull().default([]),
  segments: jsonb("segments").$type<Segment[]>().notNull().default([]),
  landedCost: doublePrecision("landed_cost").notNull().default(0),
  sourceUrl: text("source_url").notNull().default(""),
  stock: integer("stock").notNull().default(0),
  discountPercent: doublePrecision("discount_percent").notNull().default(0),
  shippingPrice: doublePrecision("shipping_price").notNull().default(0),
  active: boolean("active").notNull().default(true),
});

export const grupos = pgTable("grupos", {
  id: text("id").primaryKey(),
  seq: serial("seq"),
  slug: text("slug").notNull().unique(),
  name: text("name").notNull(),
  emoji: text("emoji").notNull().default("🗂️"),
  description: text("description"),
  color: text("color"),
  createdAt: text("created_at").notNull(),
});

export const businesses = pgTable("businesses", {
  id: text("id").primaryKey(),
  businessName: text("business_name").notNull(),
  type: text("type").notNull(),
  contactName: text("contact_name").notNull(),
  email: text("email").notNull().unique(),
  phone: text("phone").notNull().default(""),
  municipio: text("municipio").notNull().default(""),
  registroComerciante: text("registro_comerciante").notNull().default(""),
  status: text("status").notNull().default("pending"),
  passwordHash: text("password_hash").notNull(),
  createdAt: text("created_at").notNull(),
  notes: text("notes"),
});

export const orders = pgTable("orders", {
  id: text("id").primaryKey(),
  kind: text("kind").notNull().default("b2c"),
  businessId: text("business_id"),
  customerName: text("customer_name").notNull(),
  email: text("email").notNull(),
  items: jsonb("items").$type<OrderItem[]>().notNull().default([]),
  shipping: doublePrecision("shipping").notNull().default(0),
  total: doublePrecision("total").notNull().default(0),
  status: text("status").notNull().default("nuevo"),
  paymentStatus: text("payment_status"),
  paymentMethod: text("payment_method"),
  stripeSessionId: text("stripe_session_id"),
  paymentRef: text("payment_ref"),
  createdAt: text("created_at").notNull(),
});

export const sourcingCandidates = pgTable("sourcing_candidates", {
  id: text("id").primaryKey(),
  seq: serial("seq"),
  name: text("name").notNull(),
  emoji: text("emoji").notNull().default("📦"),
  category: text("category").notNull().default("General"),
  supplier: text("supplier").notNull().default(""),
  supplierId: text("supplier_id"),
  unitCost: doublePrecision("unit_cost").notNull().default(0),
  estRetail: doublePrecision("est_retail").notNull().default(0),
  estWholesale: doublePrecision("est_wholesale"),
  moq: integer("moq"),
  trend: doublePrecision("trend").notNull().default(0),
  shipping: doublePrecision("shipping").notNull().default(0),
  stage: text("stage").notNull().default("Detectado"),
  signal: text("signal").notNull().default(""),
  sourceUrl: text("source_url"),
  notes: text("notes"),
  origin: text("origin").notNull().default("manual"),
  productId: text("product_id"),
  createdAt: text("created_at").notNull(),
});

export const suppliers = pgTable("suppliers", {
  id: text("id").primaryKey(),
  seq: serial("seq"),
  name: text("name").notNull(),
  platform: text("platform").notNull().default("Otro"),
  url: text("url"),
  contactName: text("contact_name"),
  email: text("email"),
  whatsapp: text("whatsapp"),
  country: text("country"),
  products: text("products"),
  status: text("status").notNull().default("nuevo"),
  outreachDraft: text("outreach_draft"),
  notes: text("notes"),
  createdAt: text("created_at").notNull(),
  lastContactedAt: text("last_contacted_at"),
});
