import {
  pgTable,
  text,
  integer,
  doublePrecision,
  boolean,
  jsonb,
  serial,
} from "drizzle-orm/pg-core";
import type { Badge, Segment, OrderItem } from "./types";

export const products = pgTable("products", {
  id: text("id").primaryKey(),
  seq: serial("seq"),
  slug: text("slug").notNull().unique(),
  name: text("name").notNull(),
  emoji: text("emoji").notNull().default("📦"),
  gradient: text("gradient").notNull().default(""),
  imageUrl: text("image_url"),
  category: text("category").notNull().default("General"),
  grupoIds: jsonb("grupo_ids").$type<string[]>().notNull().default([]),
  tagline: text("tagline").notNull().default(""),
  description: text("description").notNull().default(""),
  retail: doublePrecision("retail").notNull().default(0),
  wholesale: doublePrecision("wholesale").notNull().default(0),
  moq: integer("moq").notNull().default(1),
  unitsPerCase: integer("units_per_case").notNull().default(1),
  badges: jsonb("badges").$type<Badge[]>().notNull().default([]),
  tags: jsonb("tags").$type<string[]>().notNull().default([]),
  segments: jsonb("segments").$type<Segment[]>().notNull().default([]),
  landedCost: doublePrecision("landed_cost").notNull().default(0),
  sourceUrl: text("source_url").notNull().default(""),
  stock: integer("stock").notNull().default(0),
  discountPercent: doublePrecision("discount_percent").notNull().default(0),
  shippingPrice: doublePrecision("shipping_price").notNull().default(0),
  active: boolean("active").notNull().default(true),
});

export const grupos = pgTable("grupos", {
  id: text("id").primaryKey(),
  seq: serial("seq"),
  slug: text("slug").notNull().unique(),
  name: text("name").notNull(),
  emoji: text("emoji").notNull().default("🗂️"),
  description: text("description"),
  color: text("color"),
  createdAt: text("created_at").notNull(),
});

export const businesses = pgTable("businesses", {
  id: text("id").primaryKey(),
  businessName: text("business_name").notNull(),
  type: text("type").notNull(),
  contactName: text("contact_name").notNull(),
  email: text("email").notNull().unique(),
  phone: text("phone").notNull().default(""),
  municipio: text("municipio").notNull().default(""),
  registroComerciante: text("registro_comerciante").notNull().default(""),
  status: text("status").notNull().default("pending"),
  passwordHash: text("password_hash").notNull(),
  createdAt: text("created_at").notNull(),
  notes: text("notes"),
});

export const orders = pgTable("orders", {
  id: text("id").primaryKey(),
  kind: text("kind").notNull().default("b2c"),
  businessId: text("business_id"),
  customerName: text("customer_name").notNull(),
  email: text("email").notNull(),
  items: jsonb("items").$type<OrderItem[]>().notNull().default([]),
  shipping: doublePrecision("shipping").notNull().default(0),
  total: doublePrecision("total").notNull().default(0),
  status: text("status").notNull().default("nuevo"),
  paymentStatus: text("payment_status"),
  paymentMethod: text("payment_method"),
  stripeSessionId: text("stripe_session_id"),
  paymentRef: text("payment_ref"),
  createdAt: text("created_at").notNull(),
});

export const sourcingCandidates = pgTable("sourcing_candidates", {
  id: text("id").primaryKey(),
  seq: serial("seq"),
  name: text("name").notNull(),
  emoji: text("emoji").notNull().default("📦"),
  category: text("category").notNull().default("General"),
  supplier: text("supplier").notNull().default(""),
  supplierId: text("supplier_id"),
  unitCost: doublePrecision("unit_cost").notNull().default(0),
  estRetail: doublePrecision("est_retail").notNull().default(0),
  estWholesale: doublePrecision("est_wholesale"),
  moq: integer("moq"),
  trend: doublePrecision("trend").notNull().default(0),
  shipping: doublePrecision("shipping").notNull().default(0),
  stage: text("stage").notNull().default("Detectado"),
  signal: text("signal").notNull().default(""),
  sourceUrl: text("source_url"),
  imageUrl: text("image_url"),
  notes: text("notes"),
  origin: text("origin").notNull().default("manual"),
  productId: text("product_id"),
  createdAt: text("created_at").notNull(),
});

export const approvalTasks = pgTable("approval_tasks", {
  id: text("id").primaryKey(),
  seq: serial("seq"),
  kind: text("kind").notNull(),
  title: text("title").notNull(),
  summary: text("summary").notNull().default(""),
  status: text("status").notNull().default("pendiente"),
  createdBy: text("created_by").notNull().default("operador"),
  payload: jsonb("payload").$type<Record<string, unknown>>(),
  relatedType: text("related_type"),
  relatedId: text("related_id"),
  decidedAt: text("decided_at"),
  decisionNote: text("decision_note"),
  executedAt: text("executed_at"),
  createdAt: text("created_at").notNull(),
});

export const agentRuns = pgTable("agent_runs", {
  id: text("id").primaryKey(),
  seq: serial("seq"),
  agent: text("agent").notNull(),
  action: text("action").notNull(),
  status: text("status").notNull().default("ok"),
  summary: text("summary").notNull().default(""),
  meta: jsonb("meta").$type<Record<string, unknown>>(),
  createdAt: text("created_at").notNull(),
});

export const quotes = pgTable("quotes", {
  id: text("id").primaryKey(),
  seq: serial("seq"),
  supplierId: text("supplier_id"),
  supplierName: text("supplier_name").notNull().default(""),
  candidateId: text("candidate_id"),
  productName: text("product_name").notNull().default(""),
  unitCost: doublePrecision("unit_cost").notNull().default(0),
  moq: integer("moq"),
  leadTimeDays: integer("lead_time_days"),
  sampleCost: doublePrecision("sample_cost"),
  shippingToPR: doublePrecision("shipping_to_pr"),
  currency: text("currency"),
  validUntil: text("valid_until"),
  notes: text("notes"),
  origin: text("origin").notNull().default("agente"),
  createdAt: text("created_at").notNull(),
});

export const purchaseOrders = pgTable("purchase_orders", {
  id: text("id").primaryKey(),
  seq: serial("seq"),
  supplierId: text("supplier_id"),
  supplierName: text("supplier_name").notNull().default(""),
  candidateId: text("candidate_id"),
  productId: text("product_id"),
  quoteId: text("quote_id"),
  productName: text("product_name").notNull().default(""),
  qty: integer("qty").notNull().default(0),
  unitCost: doublePrecision("unit_cost").notNull().default(0),
  shippingCost: doublePrecision("shipping_cost"),
  total: doublePrecision("total").notNull().default(0),
  currency: text("currency"),
  status: text("status").notNull().default("borrador"),
  paymentMethod: text("payment_method"),
  expectedAt: text("expected_at"),
  notes: text("notes"),
  createdBy: text("created_by").notNull().default("operador"),
  createdAt: text("created_at").notNull(),
});

export const shipments = pgTable("shipments", {
  id: text("id").primaryKey(),
  seq: serial("seq"),
  purchaseOrderId: text("purchase_order_id").notNull(),
  productName: text("product_name").notNull().default(""),
  carrier: text("carrier"),
  tracking: text("tracking"),
  status: text("status").notNull().default("preparando"),
  etaAt: text("eta_at"),
  notes: text("notes"),
  createdBy: text("created_by").notNull().default("operador"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at"),
});

export const inventoryMovements = pgTable("inventory_movements", {
  id: text("id").primaryKey(),
  seq: serial("seq"),
  productId: text("product_id").notNull(),
  productName: text("product_name").notNull().default(""),
  delta: integer("delta").notNull().default(0),
  reason: text("reason").notNull().default("ajuste"),
  ref: text("ref"),
  note: text("note"),
  createdBy: text("created_by").notNull().default("operador"),
  createdAt: text("created_at").notNull(),
});

export const campaigns = pgTable("campaigns", {
  id: text("id").primaryKey(),
  seq: serial("seq"),
  name: text("name").notNull(),
  productIds: jsonb("product_ids").$type<string[]>().notNull().default([]),
  segment: text("segment"),
  discountPercent: doublePrecision("discount_percent").notNull().default(0),
  startsAt: text("starts_at"),
  endsAt: text("ends_at"),
  status: text("status").notNull().default("borrador"),
  copy: text("copy"),
  createdBy: text("created_by").notNull().default("operador"),
  createdAt: text("created_at").notNull(),
});

export const suppliers = pgTable("suppliers", {
  id: text("id").primaryKey(),
  seq: serial("seq"),
  name: text("name").notNull(),
  platform: text("platform").notNull().default("Otro"),
  url: text("url"),
  contactName: text("contact_name"),
  email: text("email"),
  whatsapp: text("whatsapp"),
  country: text("country"),
  products: text("products"),
  status: text("status").notNull().default("nuevo"),
  outreachDraft: text("outreach_draft"),
  notes: text("notes"),
  createdAt: text("created_at").notNull(),
  lastContactedAt: text("last_contacted_at"),
});
